export const CREATE_VENUE_REQUEST = "CREATE_VENUE_REQUEST";
export const CREATE_VENUE_SUCCESS = "CREATE_VENUE_SUCCESS";
export const CREATE_VENUE_FAIL = "CREATE_VENUE_FAIL";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

